# .streamlit/secrets.toml
#[connections.postgresql]
#dialect = "postgresql"
#host = "localhost"
#port = "5432"
#database = "example"
#username = "hanaemaatella"

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1L19AF2t_svkYHtRhAgxg0vLliIklD4wKlK3AwcgiN3o/edit#gid=0"

type = "service_account"
project_id = "woven-bonbon-378617"
private_key_id = "7006e22229360c61b02ce2f75500abd1f8619fdf"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDGh6tcONt5UZom\n0zzoJcywhJGau9ZjbsOZnnQ9NYsWw/dpL5sB5dWWR12P8PkiHLSh/TNy9Tcz4/CP\nhPHuvIq07emT2GKmlQ6qfptzwiBPwIaP83tt63Zu8GPihojVET3iFJU7v4CPXI1u\nAw0DM0E6hkTi5Ygf+YSNZrwlYmV8H0k6BUrK4FciGQqTUGM0gsYmS6DIYNi2pazO\nQcQMtNf5KhkP0h6Q7buDfd2oZKIJA/YSxXuPQ2bYFrXsDrxsM3BACYt/00zo2D9R\npzrIMXXCypGsXRLEa7NiAtlnWBs/xR8l98cQTr0YeUtE88WF2VtmAO5GYva60pe3\nL97C4HeVAgMBAAECggEADlkizNz9G7UGl5S/u6VzuDQ0k8LMmU4Zi+I0U3IptcD/\nAhajNM1oFN7eh7cqQklh0q1KiR3o2fK44Z6Bn7f3rGDfd0R1yMVQFIlm8cRPcoQf\nFYtK2eRhIF52UZpYjFGdL9g9+t35zCKrxA4rZBZRugmXM/DT2D+/0TpiEa+dVw2J\nNAWMLZUNipnurxRKxzGjmpu//gxWErHfAzjososaG6wAJ/tvon2I8B0VdpyNUm02\nrUX6cP7CFtX6DzINPv+UO2odoltkTvoTluv05RQizGJyQLgSps/U2v/JWoX6cYpX\nkOOyAatAqN4xzT4+UHsAUnXabAv0j09nQHvzBBFDEQKBgQDnHdP5ln7T5F69uki3\nWIrOtnRrIUPmOQTfe/MtIMYGtCYdsUg5ObDDPxcbeH6OVEc1eNsPaY1wjwG7g4So\nxn9GrW4oP6JOQa98112ti5Mw+p7/Ra/48knsF6LhRAi00ao/zrWaZ89vcqMA7iUw\nOAaA5yQzDdxDTPR/DmHaOn/8eQKBgQDb56vOlvrJfuJqaV4MXQN2dtIfo5UJPlBC\nQAQPqw8Fp5gHlcxQoXbi7+VIFNHW5xvDhULHpxCRzfTMS7nAI87ZjfCldiFWu1o8\nwx1uX48Piw4pguYaEf2xMaPcqiSRj0Z06Dqj7FdKLqQtq3ikqyzT4G/iYl3A5l7P\nIfhkQF6U/QKBgEBod6Ke5kl241BMkedGraheAKO6aYnHaiw+Bs8UyxsjKVwtA8uu\n4CwJcQ8ezWYs5otoWuQ4rkooEHuJc3b1mpK/0ms1EK5ub9GC04CB3UtRDO5nJVtj\namZ5T9MneqWpqKCPotydAZo1gGfJ9mMxud5CjDwOKMw4rgqan3qJwxFBAoGBAK8e\nuQUV2rVnpCsVqd2ynLVUPlUP0fnAc+2uSQ2pLZdVNY6kzkZPrvteC3rxiYHYHZYA\no4OXGWzjVNT0YQIQAgPiMwexIS+Ol3fX8bIZyzWXiTmpklCkjyDy5QkvPVvlezhS\nT5CG/6SFrBzqdnK8FkDMdI0VxI9/ZXUSGlrLoAaJAoGAPEFZKLXHeZvh48RZu+03\nwMWeC7t9BeD3jCcky2NQKANfPsJpoTrWZJ/Kbqkm8GQvE2LcFBHQfJPe7d7lnJQt\n1ne3v6CVZ524+y4lPFuHPm+mZdw/2RYOsifA5E8TRb9IrGLDoqbN0qFRnmId0Pju\nE98wl0cjEiEYHnKSb8cUIM4=\n-----END PRIVATE KEY-----\n"
client_email = "streamlit@woven-bonbon-378617.iam.gserviceaccount.com"
client_id = "115222916492290292707"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit%40woven-bonbon-378617.iam.gserviceaccount.com"
